name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Server
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.production
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-mongodb-api:latest